name: CI-dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Install
        run: npm install
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: hg-jarlinghaus/aws-cdk-github-actions@v1.2.3
        with:
          cdk_subcommand: deploy